config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    current_user = User.find_by_id(request.session[:user_id])
    current_user.present? && current_user.admin?
  end
end

Rails.application.routes.draw do
  get 'search/find'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  use_doorkeeper
  get 'oauths/oauth'
  get 'oauths/callback'
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get '/users/email', to: 'users#email'
  patch '/users/submit_email', to: 'users#submit_email'

  get 'signup' => 'users#new', :as => :signup
  get 'signin' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'search' => 'search#find', :as => :search

  resources :tags, only: [:index, :show]

  concern :votable do
    patch :upvote, on: :member
    patch :downvote, on: :member
  end

  resources :users, concerns: :votable do
    member do
      get :activate
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]

  root 'questions#index'

  concern :commentable do
    resources :comments, only: [:show, :create, :update, :destroy], concerns: :votable, shallow: true
  end

  resources :questions, concerns: [:commentable, :votable] do
    resources :answers, only: [:index, :edit, :update, :create, :destroy], concerns: [:commentable, :votable], shallow: true do
      patch 'mark', on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only:[:index, :show, :create], shallow: true do
        resources :answers, only:[:index, :show, :create]
      end
    end
  end

end

app/models/user.rb
# create_table :users, force: true do |t|
#   t.string   :email,                                   null: false
#   t.string   :crypted_password,                        null: false
#   t.string   :salt,                                    null: false
#   t.datetime :created_at
#   t.datetime :updated_at
#   t.integer  :questions_count,             default: 0
#   t.integer  :answers_count,               default: 0
#   t.integer  :comments_count,              default: 0
#   t.string   :screen_name
#   t.string   :avatar
#   t.string   :activation_state
#   t.string   :activation_token
#   t.datetime :activation_token_expires_at
#   t.boolean  :admin
#   t.integer  :rating,                      default: 0
# end
#
# add_index :users, [:activation_token], name: :index_users_on_activation_token, using: :btree
# add_index :users, [:email], name: :index_users_on_email, unique: true, using: :btree

class User < ActiveRecord::Base
  include Votable

  authenticates_with_sorcery!
  has_many :questions
  has_many :answers
  has_many :comments

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  validates :password, length: { minimum: 6 }, presence: true
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, uniqueness: true

  mount_uploader :avatar, AvatarUploader

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  def user
    self
  end

  def self.setup_oauth_user(provider, user)
    user.email = "#{user.screen_name.downcase}@#{provider}.com" unless user.email
    random_password = rand(36**8).to_s(36)
    user.password = random_password
    user.password_confirmation = random_password
    user
  end

  def update_rating(points)
    rating = user.rating
    user.update_attribute(:rating, rating + points)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include VotableController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_filter :require_login, only: [:email, :submit_email]
  authorize_resource

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end


  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        auto_login(@user)
        format.html { redirect_to root_path, notice: 'Welcome! You have signed up successfuly.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to login_path, :notice => 'User was successfully activated.'
    else
      not_authenticated
    end
  end

  def email
    @user = current_user
    @user.email = ''
  end

  def submit_email
    current_user.update_attribute(:email, user_email_params[:email])
    UserMailer.activation_needed_email(current_user).deliver
    redirect_to root_path, :notice => 'Email was successfuly updated'
  end

  private
    def set_resource
      @resource = set_user
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_email_params
      params.require(:user).permit(:email)
    end

    def user_params
      params.require(:user).permit(:email, :screen_name, :password, :password_confirmation, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :screen_name
  .field
    = f.input :email
  .field
    = f.input :password
  .field
    = f.input :password_confirmation
  .field
    = f.input :avatar
  .actions
    = f.button :submit, 'Sign Up'

app/views/users/edit.html.haml
%h1 Editing user

= image_tag @user.avatar.url
= render 'form'

app/views/users/email.html.haml
= simple_form_for @user, url: {controller: 'users', action: 'submit_email'} do |user|
  = user.input :email
  = user.button :submit, 'Submit'

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Email
      %th
      %th
      %th
      
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 Registration

= render 'form'

app/views/users/show.html.haml
= image_tag @user.avatar.url

%p
  %span.vote-form
    = link_to '+', upvote_user_path(@user), class: 'btn btn-default btn-xs vote', method: :patch, remote: true
    %span.vote{data: { resource: 'user', id: @user.id }} #{@user.total_points}
    = link_to '-', downvote_user_path(@user), class: 'btn btn-default btn-xs vote', method: :patch, remote: true
%p
  %b Screen Name:
  = @user.screen_name
%p
  %b Email:
  = @user.email

.row.stats
  .col-md-3
    .circle #{@user.questions.size}
    questions
  .col-md-3
    .circle #{@user.answers.size}
    answers
  .col-md-3
    .circle #{@user.comments.size}
    comments
  .col-md-3
    .circle 0
    reputation

= render 'questions/questions', questions: @user.questions