config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    current_user = User.find_by_id(request.session[:user_id])
    current_user.present? && current_user.admin?
  end
end

Rails.application.routes.draw do
  get 'search/find'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  use_doorkeeper
  get 'oauths/oauth'
  get 'oauths/callback'
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get '/users/email', to: 'users#email'
  patch '/users/submit_email', to: 'users#submit_email'

  get 'signup' => 'users#new', :as => :signup
  get 'signin' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'search' => 'search#find', :as => :search

  resources :tags, only: [:index, :show]

  concern :votable do
    patch :upvote, on: :member
    patch :downvote, on: :member
  end

  resources :users, concerns: :votable do
    member do
      get :activate
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]

  root 'questions#index'

  concern :commentable do
    resources :comments, only: [:show, :create, :update, :destroy], concerns: :votable, shallow: true
  end

  resources :questions, concerns: [:commentable, :votable] do
    resources :answers, only: [:index, :edit, :update, :create, :destroy], concerns: [:commentable, :votable], shallow: true do
      patch 'mark', on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only:[:index, :show, :create], shallow: true do
        resources :answers, only:[:index, :show, :create]
      end
    end
  end

end

app/views/shared/_attachments_form.html.haml
%div= link_to 'attach files', '#', class: 'attach-link', data: { resource: resource }
.attachment-fields

app/views/shared/_bootstrap_edit_form.html.haml
- cache 'modal' do
  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} &times;
            %span.sr-only Close
          %h4#myModalLabel.modal-title Edit
        .modal-body
        .modal-footer
          %button.btn.btn-primary{:type => "button",  :id => "save-button" } Save

app/views/shared/_subscribe.html.haml
= link_to "Subscribe | #{@question.subscriptions.size}", question_subscriptions_path(@question),
   method: :post, remote: true, class: 'btn btn-default btn-sm'

app/views/shared/_tags.html.haml
.tags
  - question.tags.each do |tag|
    %span.tag
      = link_to tag.tag_name, tag_path(tag)

app/views/shared/_top_tags.html.haml
- cache @tags do
  %h4 Popular tags
  - @tags.each do |tag|
    %p
    %span.tag
      = link_to "#{tag.tag_name}", tag_path(tag)
    x #{tag.questions.size}

app/views/shared/_unsubscribe.html.haml
= link_to "Unsubscribe | #{@question.subscriptions.size}", subscription_path(@subscription),
  method: :delete, remote: true, class: 'btn btn-default btn-sm'

app/views/shared/_user.html.haml
%div.user-info
  %span.time
    = resource.created_at
  by
  = image_tag resource.user.avatar.thumb.url, height: 15
  %span.user
    = link_to resource.user.screen_name, user_path(resource.user)