config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    current_user = User.find_by_id(request.session[:user_id])
    current_user.present? && current_user.admin?
  end
end

Rails.application.routes.draw do
  get 'search/find'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  use_doorkeeper
  get 'oauths/oauth'
  get 'oauths/callback'
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get '/users/email', to: 'users#email'
  patch '/users/submit_email', to: 'users#submit_email'

  get 'signup' => 'users#new', :as => :signup
  get 'signin' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'search' => 'search#find', :as => :search

  resources :tags, only: [:index, :show]

  concern :votable do
    patch :upvote, on: :member
    patch :downvote, on: :member
  end

  resources :users, concerns: :votable do
    member do
      get :activate
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]

  root 'questions#index'

  concern :commentable do
    resources :comments, only: [:show, :create, :update, :destroy], concerns: :votable, shallow: true
  end

  resources :questions, concerns: [:commentable, :votable] do
    resources :answers, only: [:index, :edit, :update, :create, :destroy], concerns: [:commentable, :votable], shallow: true do
      patch 'mark', on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only:[:index, :show, :create], shallow: true do
        resources :answers, only:[:index, :show, :create]
      end
    end
  end

end

app/models/answer.rb
# create_table :answers, force: true do |t|
#   t.text     :body
#   t.datetime :created_at
#   t.datetime :updated_at
#   t.integer  :question_id
#   t.integer  :user_id
#   t.boolean  :best,        default: false
# end
#
# add_index :answers, [:user_id], name: :index_answers_on_user_id, using: :btree

class Answer < ActiveRecord::Base
  include Votable

  belongs_to :question, counter_cache: true
  belongs_to :user, counter_cache: true
  has_many :comments, as: :commentable
  has_many :attachments, as: :attachable

  accepts_nested_attributes_for :attachments

  validates :body, presence: true, length: { maximum: GlobalConstants::ANSWER_BODY_MAX_LENGTH }
  validates :question_id, :user_id, presence: true

  after_create :send_notification

  default_scope -> { order('created_at ASC') }

  def mark_best
    Answer.transaction do
      begin
        Answer.where(question: self.question).update_all(best: false)
        self.best = true
        self.user.update_rating(3)
        self.save
      rescue Exception
        raise ActiveRecord::Rollback
      end
    end
  end

  def send_notification
    question.subscriptions.each do |subscription|
      UserMailer.delay.new_question_answer(subscription.user, question, self) unless self.user == subscription.user
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include VotableController
  include TopTags

  before_action :load_question, only: [:index, :create]
  # before_filter :require_login, only: [:create, :destroy, :update, :edit]
  before_action :load_answer, only: [:edit, :update, :destroy, :mark]
  before_action :load_subscription, only: [:index]
  # before_filter :require_owning_object, only: [:edit, :update, :destroy]

  authorize_resource

  respond_to :json, only: [:index, :mark]
  respond_to :js, only: [:create, :edit, :update]
  respond_to :html, only: [:index, :destroy]

  def new
    @answer = @question.build
  end

  def index
    @answers = @question.answers
    respond_with(@answers)
  end

  def edit
    respond_to :html, :js
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def create
    @answer = @question.answers.create(answer_params)
    publish_answer if @answer.persisted?
    respond_with @answer
  end

  def destroy
    @answer.destroy
    respond_with(@question, location: question_answers_url(@question))
  end

  def mark
    @answer.mark_best
    respond_with(@answer)
  end

  private
    def set_resource
      @resource = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body, attachments_attributes: [:file]).merge(user: current_user)
    end

    def load_answer
      @answer = Answer.includes(:question).find(params[:id])
      @question = @answer.question
      @object = @answer
    end

    def publish_answer
      pub_json = render_to_string(template: 'answers/show.json.jbuilder', locals: {answer: @answer} )
      PrivatePub.publish_to "/questions/#{@question.id}/answers", answer: pub_json
    end

    def load_subscription
      @subscription = @question.subscriptions.find_by(user: current_user, question: @question)
    end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:index, :create]

  def index
    respond_with @question.answers
  end

  def show
    respond_with Answer.find(params[:id]), serializer: SingleAnswerSerializer, root: 'answer'
  end

  def create
    answer = @question.answers.create(answer_params)
    respond_with answer
  end

  private
  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body).merge(user: current_resource_owner)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer_form.html.haml
.answer-errors
= simple_form_for @answer, method: :patch, html: { id: 'edit-form' }, remote: true   do |f|
  = f.input :body, input_html: { rows: 6 }

app/views/answers/_answers.html.haml
%h2{style: 'background-color:#bbb;color:#fff; padding: 5px 5px;'} #{@question.answers.size} answers
- @question.answers.each do |answer|
  %p
    = answer.body
    = render 'attachments', resource: answer
    .answer-footer
      %span.user
        = link_to answer.user.screen_name, user_path(answer.user)
      - if current_user == answer.user
        |
        = link_to 'edit', edit_answer_path(answer), data: { question_id: @question.id }, remote: true
        |
        = link_to 'x', answer, data: {question_id: @question.id}, method: :delete, data: { confirm: 'You sure?' }
    = render 'comments', parent: answer

app/views/answers/_attachments.html.haml
- if resource.attachments.count > 0
  .attachments
    Next files are attached:
    %br
    - resource.attachments.each do |a|
      = link_to a.file.identifier, a.file.url, class: 'btn btn-xs btn-default'

app/views/answers/_comments.html.haml
.comments{ data: { resource: parent.class.to_s.downcase + 's', id: parent.id } }
  - if parent.comments.any?
    - parent.comments.each do |comm|
      .comment{data: {id: comm.id}}
        %span.comment-body
          - cache comm do
            = comm.body
          = render 'shared/user', resource: comm
        - if current_user == comm.user
          |
          = link_to 'edit', '#', class: 'edit-comment'
          |
          = link_to 'x', comment_path(comm), method: :delete, remote: true, class: 'remove-comment', data: { type: :json }
- if current_user
  .comment-form
    = link_to 'add a comment', '#', id: 'add-comment', data: { resource: parent.class.to_s.downcase + 's', id: parent.id }

app/views/answers/_comments_to_question.html.haml
- if @question.comments.any?
  - @question.comments.each do |comm|
    .comment
      = comm.body
      - if current_user == comm.user
        |
        = link_to 'x', comm, method: :delete
  - if current_user
    .comment-form
      -#= simple_form_for [@question, @new_comment], remote: true, data: { type: :json } do |c|
      -#  = c.input :body
      -#  = c.button :submit
      = link_to 'add a comment', '#', id: 'add-comment', data: { resource: 'questions', id: @question.id }

app/views/answers/_edit_form.html.haml
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        %h4#myModalLabel.modal-title Edit answer
      .modal-body
      .modal-footer
        %button.btn.btn-primary{:type => "button"} Save

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
    $('.answer-errors').html('<%= @answer.errors.full_messages.join("/n") %>');
<% else %>
    $('.answers').html('<%= j render 'answers/answers' %>');
    $('#answer_body').val('');
<% end %>

app/views/answers/edit.html.haml
- provide(:title, 'Edit answer')
= form_for @answer do |a|
  = a.label :body
  %br
  = a.text_area :body
  = a.submit 'Update answer'

app/views/answers/edit.js.erb
$('.modal-body').html('<%= j render 'answer_form' %>');
$('#myModal').modal();

app/views/answers/index.html.haml
= javascript_include_tag 'answers'

= provide(:title, 'Show question')
= render 'shared/bootstrap_edit_form'
.row
  .col-md-10
    - cache @question do
      .full-question{data: {id: @question.id, user: @question.user.id}}
        .qtitle= @question.title
        %span.vote-form
          = link_to '+', upvote_question_path(@question), class: 'btn btn-default btn-xs vote', method: :patch, remote: true
          %span.vote{data: { resource: 'question', id: @question.id }} #{@question.total_points}
          = link_to '-', downvote_question_path(@question), class: 'btn btn-default btn-xs vote', method: :patch, remote: true
          .qbody= @question.body
        = render 'attachments', resource: @question
      .question-footer
        = render 'shared/tags', question: @question
        = render 'shared/user', resource: @question
        - if current_user == @question.user
          |
          = link_to 'edit', edit_question_path(@question), remote: true
          = link_to 'x', @question, method: :delete, data: { confirm: 'You sure?' }
        - if logged_in?
          .subscription
            - if @subscription.nil?
              = render 'shared/subscribe'
            - else
              = render 'shared/unsubscribe'
        = render 'comments', parent: @question
    %hr
    .answers
      -#= render 'answers'
    %br
      - if logged_in?
        = simple_form_for (@question.answers.build), url: question_answers_path(@question), remote: true do |a|
          = a.label :body, 'Your answer'
          .answer-errors
          = a.input :body, label: false, input_html: { rows: 6 }
          = render 'shared/attachments_form', resource: 'answer'
          = a.button :submit, 'Create'
  .col-md-2
    = render 'shared/top_tags'

= subscribe_to "/questions/#{@question.id}/answers" unless Rails.env.test?
= subscribe_to "/questions/#{@question.id}/comments" unless Rails.env.test?

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    $('.answer-errors').html('<%= @answer.errors.to_a.join(',') %>')
<% else %>
    $('.answers').html("<%= j render 'answers/answers' %>");
    $('#myModal').modal('hide');
<% end %>