config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    current_user = User.find_by_id(request.session[:user_id])
    current_user.present? && current_user.admin?
  end
end

Rails.application.routes.draw do
  get 'search/find'

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  use_doorkeeper
  get 'oauths/oauth'
  get 'oauths/callback'
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get '/users/email', to: 'users#email'
  patch '/users/submit_email', to: 'users#submit_email'

  get 'signup' => 'users#new', :as => :signup
  get 'signin' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get 'search' => 'search#find', :as => :search

  resources :tags, only: [:index, :show]

  concern :votable do
    patch :upvote, on: :member
    patch :downvote, on: :member
  end

  resources :users, concerns: :votable do
    member do
      get :activate
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]

  root 'questions#index'

  concern :commentable do
    resources :comments, only: [:show, :create, :update, :destroy], concerns: :votable, shallow: true
  end

  resources :questions, concerns: [:commentable, :votable] do
    resources :answers, only: [:index, :edit, :update, :create, :destroy], concerns: [:commentable, :votable], shallow: true do
      patch 'mark', on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only:[:index, :show, :create], shallow: true do
        resources :answers, only:[:index, :show, :create]
      end
    end
  end

end

app/views/layouts/_footer.html.haml
%footer.footer
  %hr
  %small camelCase Studio, 2015
  -#= debug(params) if Rails.env.development?

app/views/layouts/_header.html.haml
%header.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %span#logo
        = link_to root_path do
          = "Stack"
          = image_tag '/images/clown.jpg', height: 30
          = "clown"
      %nav
        = link_to 'Ask question', new_question_path, class: 'btn btn-default navbar-btn', style: 'margin-left: 25px'
        %form.navbar-form.navbar-right{role: 'search', action: '/search', method: 'get'}
          .form-group
            %input.form-control{type: 'text', placeholder: 'Search', name:'q'}
          %button.btn.btn-default{type: 'submit'} Go
        %ul.nav.navbar-nav.pull-right
          - if current_user
            %li= link_to 'Edit Profile', edit_user_path(current_user.id)
            %li= link_to 'Logout', :logout, method: :post
          - else
            %li= link_to 'Register', signup_path
            %li= link_to 'Login', :login

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackclown</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= include_gon %>

<%= render 'layouts/header' %>
<div id="user-info" style="display: none"
     data-user-signed="<%= !current_user.nil? %>" <%= "data-user-id=#{current_user.id}" if current_user %> />

</div>
<div class="container">
  <div class="row">
      <% if flash[:notice]  %>
          <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= flash[:notice] %>
          </div>
      <% end %>
      <% if flash[:alert]  %>
          <div class="alert alert-warning alert-dismissible" role="alert"><%= flash[:alert] %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      <% end %>
  </div>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>